# Generated by Django 5.0.7 on 2024-08-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded'),
        ),
    ]
